version: "3"

services:
  postgres:
    image: postgres
    hostname: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - $HOME/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_DB: computer-club-backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 8080:80
    volumes:
      - $HOME/pgadmin/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
